### ISSUE TITLE
Casting a byte to int* ?

### ISSUE THREAD

**Issue by budgetdevv** [Elskom/ZlibSharp#1]
Am I dumb or that's what you're doing?

https://github.com/Elskom/ZlibSharp/blob/f226a13a5b8faa1da608cf5b1e70ec205fa9bb23/src/ZlibSharp/ZlibSharp/ZlibHelper.cs#L49

Also why are you passing source and dest by ref, if they're already refs? Hopefully I misinterpreted everything 👀

**Comment by AraHaan** [comment]
That is because it expects a pointer and I think that it has to start at element 0, however element 0 in c# is byte so I cast it to byte*.

**Comment by budgetdevv** [comment]
No, source[0] returns a byte, which you proceeded to cast to a byte pointer...you were probably looking for 
`zs.next_in = (byte*) Unsafe.AsPointer(ref MemoryMarshal.GetArrayDataReference(source));`

However, that is also unsafe because the GC can move the array, invalidating the pointer

**Comment by budgetdevv** [comment]
What is the `zs.next_in` pointer for? Perhaps we could think of something if you elaborate on that

**Comment by AraHaan** [comment]
I think it controls the data passed into zlib, and the next_out is the data from zlib I think. But yes I think you are correct in that I think the GC needs to know to not move the data on that resulting pointer until the end of scope.

**Comment by budgetdevv** [comment]
Hmmm, so `zs.next_in` is a pointer to a buffer? And `next_out` is a pointer to the processed buffer?

**Comment by AraHaan** [comment]
I believe so yes.

**Comment by budgetdevv** [comment]
I suppose `next_out` is a pointer to memory allocated by zlib? It doesn't make sense for it to be the buffer passed to zlib, since it may be smaller

**Comment by budgetdevv** [comment]
I also notice function pointers `delegate* unmanaged[Cdecl] <void*, void*> zalloc` `delegate* unmanaged[Cdecl] <void*, uint, uint> zfree`...what are they for? To allocate native memory? 

More importantly, why does `zalloc` take a void pointer and return one? 👀

**Comment by AraHaan** [comment]
> I suppose `next_out` is a pointer to memory allocated by zlib? It doesn't make sense for it to be the buffer passed to zlib, since it may be smaller

I think what they want by next_out is the pointer (to in this case my managed byte array's data) so then it can write it to that.

**Comment by AraHaan** [comment]
@budgetdevv does this issue seem resolved to you yet or are there more bugs?

**Comment by budgetdevv** [comment]
It _looks_ ok but I've yet to test it - will update here when I get to doing so

**Comment by AraHaan** [comment]
Alright

**Comment by AraHaan** [comment]
Completed in #4 I think.
