### ISSUE TITLE
Add unit tests.

### ISSUE THREAD

**Issue by AraHaan** [Elskom/ZlibSharp#2]
This needs some unit tests to verify that everything works as expected.

**Comment by AraHaan** [comment]
@budgetdevv I would assign this to you but it won't let me currently to do it.

Note: After unit tests are added and verified that it works I might add this code to replace zlib.managed in Elskom/runtime.

**Comment by budgetdevv** [comment]
What is Elskon/runtime? A fork of the runtime?

**Comment by AraHaan** [comment]
No, it's the runtime I am making which I basically migrated the sources to most of my projects to.

**Comment by AraHaan** [comment]
Merged #4.
